# Generated by Django 4.0.2 on 2022-02-26 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_episodio'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodio',
            name='filme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='episodios', to='filme.filme'),
            preserve_default=False,
        ),
    ]
